# Generated by Django 5.0.7 on 2024-09-17 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitationbookapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
