# Generated by Django 5.0.7 on 2024-09-18 14:31

import django.db.models.deletion
import uuid
import visitationbook.os.fields
import visitationbookapi.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitationbookapi', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=visitationbookapi.models.Book._generate_document_path, verbose_name='Cover Image')),
                ('original_file_name', models.CharField(blank=True, help_text='Original file name', max_length=255, null=True)),
                ('content_type', models.CharField(blank=True, help_text='The file extension', max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('created_by', visitationbook.os.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Added by')),
                ('updated_by', visitationbook.os.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['title', 'price'],
            },
        ),
        migrations.CreateModel(
            name='BookPurchase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_cover', models.ImageField(blank=True, help_text="User's custom cover if provided", null=True, upload_to=visitationbookapi.models.BookPurchase._generate_custom_cover_path, verbose_name='Custom Cover Image')),
                ('original_file_name', models.CharField(blank=True, help_text='Original file name', max_length=255, null=True)),
                ('content_type', models.CharField(blank=True, help_text='The file extension', max_length=255, null=True)),
                ('payment_status', models.BooleanField(default=False, verbose_name='Payment Status')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Purchase Date')),
                ('deceased_image', models.ImageField(blank=True, null=True, upload_to=visitationbookapi.models.BookPurchase._generate_deceased_image_path, verbose_name='Deceased Image')),
                ('deceased_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Deceased Name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Date of Death')),
                ('allow_picture', models.BooleanField(default=False, verbose_name='Allow guest to add a picture to their name')),
                ('allow_name', models.BooleanField(default=True, verbose_name='Allow guest to add their name')),
                ('allow_address', models.BooleanField(default=False, verbose_name='Allow guest to add their address')),
                ('allow_email', models.BooleanField(default=True, verbose_name='Allow guest to add their email')),
                ('allow_special_notes', models.BooleanField(default=True, verbose_name='Allow special notes to the family')),
                ('custom_field_25', models.BooleanField(default=False, verbose_name='Custom field (video/media link) $25.00')),
                ('custom_field_50', models.BooleanField(default=False, verbose_name='Custom field (video/media link) $50.00')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='visitationbookapi.book', verbose_name='Book')),
                ('created_by', visitationbook.os.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Added by')),
                ('updated_by', visitationbook.os.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_purchases', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Book Purchase',
                'verbose_name_plural': 'Book Purchases',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='GuestInfo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Guest Name')),
                ('guest_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Guest Address')),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Guest Email')),
                ('special_notes', models.TextField(blank=True, null=True, verbose_name='Special Notes to the Family')),
                ('custom_field_video_25', models.URLField(blank=True, null=True, verbose_name='Custom field (video/media link) $25.00')),
                ('custom_field_video_50', models.URLField(blank=True, null=True, verbose_name='Custom field (video/media link) $50.00')),
                ('book_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_infos', to='visitationbookapi.bookpurchase', verbose_name='Book Purchase')),
                ('created_by', visitationbook.os.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Added by')),
                ('updated_by', visitationbook.os.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'verbose_name': 'Guest Info',
                'verbose_name_plural': 'Guest Infos',
            },
        ),
        migrations.CreateModel(
            name='Obituary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deceased_name', models.CharField(max_length=255, verbose_name='Deceased Name')),
                ('book_cover', models.ImageField(blank=True, null=True, upload_to='obituary_covers/', verbose_name='Book Cover')),
                ('obituary_pdf', models.FileField(blank=True, null=True, upload_to=visitationbookapi.models.Obituary._generate_document_path, verbose_name='Obituary PDF')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('date_of_death', models.DateField(verbose_name='Date of Death')),
                ('created_by', visitationbook.os.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Added by')),
                ('updated_by', visitationbook.os.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obituaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Obituary',
                'verbose_name_plural': 'Obituaries',
                'ordering': ['-date_of_death', 'deceased_name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_holder', models.CharField(max_length=255, verbose_name='Card Holder')),
                ('card_token', models.CharField(max_length=255, verbose_name='Card Token')),
                ('card_number', models.CharField(max_length=16, verbose_name='Card Number')),
                ('card_brand', models.CharField(max_length=50, verbose_name='Card Brand')),
                ('card_cvv', models.CharField(max_length=3, verbose_name='Card CVV')),
                ('expiry_month', models.IntegerField(verbose_name='Expiry Month')),
                ('expiry_year', models.IntegerField(verbose_name='Expiry Year')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('created_by', visitationbook.os.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Added by')),
                ('updated_by', visitationbook.os.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['-is_default', 'expiry_year', 'expiry_month'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tax')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Discount')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Payment Date')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], max_length=20, verbose_name='Payment Status')),
                ('created_by', visitationbook.os.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Added by')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='visitationbookapi.paymentmethod')),
                ('updated_by', visitationbook.os.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddField(
            model_name='bookpurchase',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_purchases', to='visitationbookapi.paymenttransaction', verbose_name='Payment Transaction'),
        ),
    ]
