# Generated by Django 5.0.7 on 2024-09-18 22:44

import visitationbookapi.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitationbookapi', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', visitationbookapi.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
