# Generated by Django 5.0.7 on 2024-09-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitationbookapi', '0006_user_content_type_user_original_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Card Brand'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Card Token'),
        ),
    ]
