# Generated by Django 5.0.7 on 2024-09-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitationbookapi', '0008_remove_paymentmethod_card_cvv_paymentmethod_card_cvc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card_cvc',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card_token',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Added On'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='last4',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Last 4 digits'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='stripe_payment_method_id',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_holder',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Card Holder'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiry_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='Expiry Month'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiry_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Expiry Year'),
        ),
    ]
