# Generated by Django 5.0.7 on 2024-09-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitationbookapi', '0009_remove_paymentmethod_card_cvc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiry_month',
            field=models.IntegerField(null=True, verbose_name='Expiry Month'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiry_year',
            field=models.IntegerField(null=True, verbose_name='Expiry Year'),
        ),
    ]
