# Generated by Django 5.0.7 on 2024-09-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitationbookapi', '0010_alter_paymentmethod_expiry_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
