# Generated by Django 5.0.7 on 2024-09-22 20:58

import visitationbookapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitationbookapi', '0013_bookpurchase_obituary'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestinfo',
            name='guest_picture',
            field=models.ImageField(blank=True, help_text="Guest's Picture if required", null=True, upload_to=visitationbookapi.models.GuestInfo._generate_guest_picture_path, verbose_name='Guest Picture'),
        ),
    ]
