# Generated by Django 5.0.7 on 2024-10-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitationbookapi', '0015_bookpurchase_is_both'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpurchase',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='bookpurchase',
            name='original_file_name',
        ),
        migrations.AddField(
            model_name='bookpurchase',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Is complete checking'),
        ),
        migrations.AddField(
            model_name='bookpurchase',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='book_purchase_pdfs/'),
        ),
        migrations.AddField(
            model_name='obituary',
            name='is_both',
            field=models.BooleanField(default=False, verbose_name='Is both checking'),
        ),
    ]
