# Generated by Django 5.0.7 on 2024-10-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitationbookapi', '0016_remove_bookpurchase_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpurchase',
            name='visit_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Visit Count'),
        ),
        migrations.AddField(
            model_name='obituary',
            name='visit_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Visit Count'),
        ),
    ]
