# Generated by Django 5.0.7 on 2024-10-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitationbookapi', '0018_user_facebook_id_user_google_id_user_social_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpurchase',
            name='allow_address',
            field=models.BooleanField(default=True, verbose_name='Allow guest to add their address'),
        ),
        migrations.AlterField(
            model_name='bookpurchase',
            name='allow_special_notes',
            field=models.BooleanField(default=False, verbose_name='Allow special notes to the family'),
        ),
    ]
