# Generated by Django 5.0.7 on 2024-10-30 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitationbookapi', '0020_remove_bookpurchase_custom_field_25_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obituary',
            options={'ordering': ['deceased_name'], 'verbose_name': 'Obituary', 'verbose_name_plural': 'Obituaries'},
        ),
    ]
