# Generated by Django 5.0.7 on 2024-11-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitationbookapi', '0021_alter_obituary_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestinfo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Guest Info', 'verbose_name_plural': 'Guest Infos'},
        ),
        migrations.AlterModelOptions(
            name='obituary',
            options={'ordering': ['-created_at'], 'verbose_name': 'Obituary', 'verbose_name_plural': 'Obituaries'},
        ),
        migrations.RemoveField(
            model_name='obituary',
            name='date_of_death',
        ),
    ]
