# Generated by Django 5.0.7 on 2024-12-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitationbookapi', '0022_alter_guestinfo_options_alter_obituary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpurchase',
            name='attending_note',
            field=models.TextField(blank=True, help_text='HTML formatted thank you message from the book purchaser', null=True, verbose_name='Attending Note'),
        ),
    ]
