# Generated by Django 5.0.7 on 2025-01-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitationbookapi', '0023_bookpurchase_attending_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpurchase',
            name='attending_note_pdf',
            field=models.FileField(blank=True, null=True, upload_to='book_purchase_attending_note_pdfs/'),
        ),
    ]
