# Generated by Django 5.0.7 on 2025-01-11 00:05

import django.db.models.deletion
import visitationbook.os.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitationbookapi', '0024_bookpurchase_attending_note_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuneralHomeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('latest_invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('books_created', models.IntegerField(default=0, help_text='Number of books created under this subscription')),
                ('created_by', visitationbook.os.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Added by')),
                ('updated_by', visitationbook.os.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='bookpurchase',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_purchases', to='visitationbookapi.funeralhomesubscription'),
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('small', 'Small Funeral Home'), ('medium', 'Medium Size Funeral Home'), ('large', 'Large Funeral Home')], max_length=20)),
                ('book_type', models.CharField(choices=[('visitation', 'Visitation Book Only'), ('obituary', 'Obituary Book Only'), ('both', 'Both Books')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_books', models.IntegerField(help_text='Maximum number of books allowed')),
                ('duration_months', models.IntegerField(default=12)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', visitationbook.os.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Added by')),
                ('updated_by', visitationbook.os.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'ordering': ['plan_type', 'book_type'],
                'unique_together': {('plan_type', 'book_type')},
            },
        ),
        migrations.CreateModel(
            name='SubscriptionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_by', visitationbook.os.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Added by')),
                ('updated_by', visitationbook.os.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='visitationbookapi.subscriptionplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='funeralhomesubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visitationbookapi.subscriptionplan'),
        ),
    ]
