# Generated by Django 5.0.7 on 2025-01-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitationbookapi', '0026_funeralhomesubscription_payment_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
