# Generated by Django 5.0.7 on 2025-01-27 15:17

import visitationbookapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitationbookapi', '0028_alter_funeralhomesubscription_latest_invoice_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestinfo',
            name='thank_you_pdf',
            field=models.FileField(blank=True, null=True, upload_to=visitationbookapi.models.GuestInfo._generate_thank_you_pdfs_path, verbose_name='Guest Thank You PDF'),
        ),
    ]
