services:
  visitationbook_postgres:
    image: postgres:latest
    restart: unless-stopped
    container_name: visitationbook_db
    build:
      context: ..
      dockerfile: .env/pg/Dockerfile
    networks:
      - visitationbook_backend
    volumes:
      - visitationbook_pgdata:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432

  visitationbook_pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: visitationbook_pgadmin
    ports:
      - 5050:80
    env_file:
      - .env
    depends_on:
      - visitationbook_postgres
    networks:
      - visitationbook_backend

  visitationbook_redis:
    image: redis/redis-stack:latest
    restart: unless-stopped
    container_name: visitationbook_redis
    ports:
      - "6379:6379"
    networks:
      - visitationbook_backend
    command: ["redis-server", "--appendonly", "yes", "--protected-mode", "no"]

  visitationbook_web:
    restart: unless-stopped
    container_name: visitationbook_web
    build:
      context: ..
      dockerfile: .env/python/Dockerfile
    command: /bin/sh .env/python/entrypoint.sh
    volumes:
      - ..:/home/app/web
      - visitationbook_static_volume:/home/app/web/static
      - visitationbook_media_volume:/home/app/web/media
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
      - visitationbook_backend
    depends_on:
      - visitationbook_postgres

  visitationbook_nginx:
    container_name: visitationbook_nginx
    restart: unless-stopped
    build:
      context: ..
      dockerfile: .env/nginx/Dockerfile
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - visitationbook_static_volume:/home/app/web/static
      - visitationbook_media_volume:/home/app/web/media
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/www/certbot
    networks:
      - visitationbook_backend
    ports:
      - 80:80
      - 443:443
    depends_on:
      - visitationbook_web




networks:
  visitationbook_backend:

volumes:
  visitationbook_static_volume:
  visitationbook_media_volume:
  visitationbook_pgdata:
  certbot_etc:
  certbot_var:
